//学校简介
module.exports.introduce = {
  "shortName": "广科", //学校名字两个字缩写
  "name": "广东科技学院", //学校名称
  "images": "http://img1.gtimg.com/ninja/1/2017/09/ninja150668100964231.jpg", // 首页图片地址
  "latitude": "22.97177",
  "longitude": "113.75453",
  "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],  //简介图片
  "description": "<p>广东科技学院创建于2003年，是国家教育部批准设立的一所以工学为主，管理学、经济学、文学、艺术学等多学科协调发展的全日制普通本科院校，拥有学士学位授予权，培养经济社会发展需要的高素质应用型人才。</p><br><p>学院现有全日制在校学生17106人，专任教师799人，其中具有高级职称教师和硕士及以上学位教师占专任教师的比例分别达到32%和60 %。学院设有机电工程系、计算机系、管理系、财经系、外语系、艺术设计系、公共基础课部、思想政治理论课教学部、继续教育学院、国际教育学院、创新创业学院等六系两部三院，承担国家计划内招生任务。2017年开设本科招生专业27个。</p><br><p>  学院位于东莞市南城区，东临西平湖，西接植物园，南依西湖乐园，北靠环城路，环境幽雅，交通便利，风景怡人。校园规划占地面积934亩，建筑面积52万余平方米，图书馆面积2.36万平方米，拥有各类图书236万册，教学仪器设备总值10602万余元。</p>"
}
//学校地图数据
module.exports.map = [
  {
    "name": "景点",
    "scale": 16,
    "data": [{
      "id": 1,
      "name": "东莞植物园",
      "latitude": "22.96642",
      "longitude": "113.74962",
      "iconPath": "/img/ico/jd.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "东莞植物园"
    }, {
      "id": 2,
      "name": "图书馆",
      "latitude": "22.97128",
      "longitude": "113.75467",
      "iconPath": "/img/ico/jd.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tsg2.jpg", "http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "广东科技学院图书馆"
    }, {
      "id": 3,
      "name": "体育馆",
      "latitude": "22.97243",
      "longitude": "113.75629",
      "iconPath": "/img/ico/jd.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "广东科技学院体育馆"
    }, {
      "id": 4,
      "name": "西湖乐园",
      "latitude": "22.96726",
      "longitude": "113.75763",
      "iconPath": "/img/ico/jd.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-xhly.jpg"],
      "description": "西湖乐园"
    }, {
      "id": 5,
      "name": "雅园综合市场",
      "latitude": "22.972680",
      "longitude": "113.758130",
      "iconPath": "/img/ico/jd.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "雅园综合市场"
    }]
  }, {
    "name": "教学楼",
    "scale": 16,
    "data": [{
      "id": 1,
      "name": "1号教学楼",
      "latitude": "22.97338",
      "longitude": "113.7554",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "1号教学楼"
    }, {
      "id": 2,
      "name": "2号教学楼",
      "latitude": "22.97331",
      "longitude": "113.75464",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "2号教学楼"
    }, {
      "id": 3,
      "name": "3号教学楼",
      "latitude": "22.97379",
      "longitude": "113.75627",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "3号教学楼"
    }, {
      "id": 4,
      "name": "4号教学楼",
      "latitude": "22.972841",
      "longitude": "113.755145",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "4号教学楼"
    }, {
      "id": 5,
      "name": "5号教学楼",
      "latitude": "22.973043",
      "longitude": "113.755928",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "5号教学楼"
    }, {
      "id": 6,
      "name": "6号教学楼",
      "latitude": "22.97253",
      "longitude": "113.75524",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "6号教学楼"
    }, {
      "id": 7,
      "name": "7号教学楼",
      "latitude": "22.97265",
      "longitude": "113.7558",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "7号教学楼"
    }, {
      "id": 8,
      "name": "8号教学楼",
      "latitude": "22.96993",
      "longitude": "113.75418",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "8号教学楼"
    }, {
      "id": 9,
      "name": "9号教学楼",
      "latitude": "22.96945",
      "longitude": "113.75461",
      "iconPath": "/img/ico/jxl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "9号教学楼"
    }]
  }, {
    "name": "校门",
    "scale": 16,
    "data": [{
      "id": 1,
      "name": "北门",
      "latitude": "22.97427",
      "longitude": "113.75511",
      "iconPath": "/img/ico/xm.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "北门"
    }, {
      "id": 2,
      "name": "东门",
      "latitude": "22.9732",
      "longitude": "113.75779",
      "iconPath": "/img/ico/xm.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "东门"
    }, {
      "id": 3,
      "name": "南门",
      "latitude": "22.96919",
      "longitude": "113.75486",
      "iconPath": "/img/ico/xm.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南门"
    }, {
      "id": 4,
      "name": "雅苑门",
      "latitude": "22.97718",
      "longitude": "113.75838",
      "iconPath": "/img/ico/xm.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "雅苑门"
    }]
  }, {
    "name": "食堂",
    "scale": 16,
    "data": [{
      "id": 1,
      "name": "一饭",
      "latitude": "22.974238",
      "longitude": "113.756990",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "一号饭堂：位于博苑，学校唯一设有2层的饭堂，是从雅苑宿舍到教学楼的必经之路。\n    是校内人流量最多的一个饭堂，饭菜味道大众化，适合多种人的口味，肉类丰富，种类繁多。有4毛钱和6毛钱的米饭窗口，如果打包需要加1块钱的外卖费，蔬菜跟肉类种类都是很多的，口味也大众化，而且也有炖汤提供，价格不一，最靠左边还有鸡扒饭可选择，一饭正门入口外卖摊位那里还有快餐，基本是客家人，也别有一番风味。\n  第二层特色是自助餐，菜跟肉自己挑选，然后称重算钱，15块钱一斤，饭是免费的，可以吃多少打多少，另外还有煮面食的摊位。"
    }, {
      "id": 2,
      "name": "二饭",
      "latitude": "22.970702",
      "longitude": "113.754673",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "二号饭堂：位于南苑4号宿舍的一楼，接近图书馆，环境明亮，早餐有肠粉，菜色丰富，口感鲜美，特色是现煮粥，材料可自己选择。"
    }, {
      "id": 3,
      "name": "三饭",
      "latitude": "22.970260",
      "longitude": "113.754510",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "三号饭堂：三饭与二饭相邻，在南苑1.2号宿舍的一楼，有自助餐和汤粉蒸粉肠粉，三饭的特色是煲仔饭，材料可自己选择（田鸡、鸡肉等）菜色丰富，不过早餐是4个饭堂中种类最多的，味道也都挺不错的。"
    }, {
      "id": 4,
      "name": "四饭",
      "latitude": "22.976881",
      "longitude": "113.756191",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "四号饭堂：在雅苑宿舍区，临近宿舍，方便学生就餐。目前已经改造升级完毕，环境优美，且菜式种类繁多，经过改造升级以后，目前是学校里面环境较好的饭堂。"
    }, {
      "id": 5,
      "name": "东门二三楼",
      "latitude": "22.976882",
      "longitude": "113.756131",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "东门二三楼"
    }, {
      "id": 6,
      "name": "爱时尚",
      "latitude": "22.976862",
      "longitude": "113.756231",
      "iconPath": "/img/ico/st.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "爱时尚"
    }]
  }, {
    "scale": 16,
    "name": "宿舍",
    "data": [{
      "id": 1,
      "name": "南苑1栋",
      "latitude": "22.970203",
      "longitude": "113.754367",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南苑1栋"
    }, {
      "id": 2,
      "name": "南苑2栋",
      "latitude": "22.970356",
      "longitude": "113.753884",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南苑2栋"
    }, {
      "id": 3,
      "name": "南苑3栋",
      "latitude": "22.971003",
      "longitude": "113.754002",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南苑3栋"
    }, {
      "id": 4,
      "name": "南苑4栋",
      "latitude": "22.970885",
      "longitude": "113.754544",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南苑4栋"
    }, {
      "id": 5,
      "name": "博苑1栋",
      "latitude": "22.974001",
      "longitude": "113.757033",
      "iconPath": "/img/ico/girl_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "博苑1栋"
    }, {
      "id": 6,
      "name": "博苑2栋",
      "latitude": "22.974683",
      "longitude": "113.757607",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "博苑2栋"
    }, {
      "id": 6,
      "name": "博苑3栋",
      "latitude": "22.974278",
      "longitude": "113.757591",
      "iconPath": "/img/ico/boy_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "博苑3栋"
    }, {
      "id": 7,
      "name": "博苑4栋",
      "latitude": "22.973567",
      "longitude": "113.757570",
      "iconPath": "/img/ico/girl_ss.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "博苑4栋"
    }]
  }, {
    "scale": 14,
    "name": "校园服务",
    "data": [{
      "id": 1,
      "name": "南门快递超市",
      "latitude": "22.982",
      "longitude": "113.7",
      "iconPath": "/img/ico/xyfu.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "中通、申通。。。。"
    }, {
      "id": 2,
      "name": "东门二楼快递",
      "latitude": "22.98",
      "longitude": "113.71",
      "iconPath": "/img/ico/xyfu.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "天天快递"
      }, {
        "id": 3,
        "name": "南门照相馆",
        "latitude": "22.981",
        "longitude": "113.72",
        "iconPath": "/img/ico/xyfu.png",
        "width": "30",
        "height": "30",
        "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
        "description": "南门照相馆"
    }, {
      "id": 4,
      "name": "雅园照相馆",
      "latitude": "22.982",
      "longitude": "113.725",
      "iconPath": "/img/ico/xyfu.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "南门照相馆"
    }]
  }, {
    "scale": 12,
    "name": "到处浪",
    "data": [{
      "id": 1,
      "name": "汇一城",
      "latitude": "22.97",
      "longitude": "113.7",
      "iconPath": "/img/ico/dcl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 2,
      "name": "新光明市场",
      "latitude": "22.972",
      "longitude": "113.753",
      "iconPath": "/img/ico/dcl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "西安科技大学"
    }, {
      "id": 3,
      "name": "厚街万达",
      "latitude": "22.9761",
      "longitude": "113.8",
      "iconPath": "/img/ico/dcl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 4,
      "name": "咸阳师范学院",
      "latitude": "22.92122",
      "longitude": "113.75122",
      "iconPath": "/img/ico/dcl.png",
      "width": "30",
      "height": "30",
      "img": ["http://qn.gxgk.cc/school/jd-tyg.jpg"],
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }]
  }
]
