module.exports = [
  {
    name: "景点",
    data: [{
      "id": 2,
      "name": "图书馆",
      "latitude": "22.97128",
      "longitude": "113.75467",
      "img": "/img/school/tsg.jpg",
      "description": "广东科技学院图书馆"
    }, {
      "id": 3,
      "name": "体育馆",
      "latitude": "22.97243",
      "longitude": "113.75629",
      "img": "/img/school/tsg.jpg",
      "description": "广东科技学院体育馆"
    }, {
      "id": 4,
      "name": "西湖乐园",
      "latitude": "22.96726",
      "longitude": "113.75763",
      "img": "/img/school/tsg.jpg",
      "description": "西湖乐园"
    }, {
      "id": 6,
      "name": "东莞植物园",
      "latitude": "22.96642",
      "longitude": "113.74962",
      "img": "/img/school/tsg.jpg",
      "description": "东莞植物园"
    }]
  }, {
    name: "教学楼",
    data: [{
      "id": 1,
      "name": "1号教学楼",
      "latitude": "22.97338",
      "longitude": "113.7554",
      "img": "/img/school/tsg.jpg",
      "description": "1号教学楼"
    }, {
      "id": 2,
      "name": "2号教学楼",
      "latitude": "22.97331",
      "longitude": "113.75464",
      "img": "/img/school/tsg.jpg",
      "description": "2号教学楼"
    }, {
      "id": 3,
      "name": "3号教学楼",
      "latitude": "22.97379",
      "longitude": "113.75627",
      "img": "/img/school/tsg.jpg",
      "description": "3号教学楼"
    }, {
      "id": 4,
      "name": "4号教学楼",
      "latitude": "22.97291",
      "longitude": "113.75543",
      "img": "/img/school/tsg.jpg",
      "description": "4号教学楼"
    }, {
      "id": 5,
      "name": "5号教学楼",
      "latitude": "22.97315",
      "longitude": "113.75646",
      "img": "/img/school/tsg.jpg",
      "description": "5号教学楼"
    }, {
      "id": 6,
      "name": "6号教学楼",
      "latitude": "22.97253",
      "longitude": "113.75524",
      "img": "/img/school/tsg.jpg",
      "description": "6号教学楼"
    }, {
      "id": 7,
      "name": "7号教学楼",
      "latitude": "22.97265",
      "longitude": "113.7558",
      "img": "/img/school/tsg.jpg",
      "description": "7号教学楼"
    }, {
      "id": 8,
      "name": "8号教学楼",
      "latitude": "22.96993",
      "longitude": "113.75418",
      "img": "/img/school/tsg.jpg",
      "description": "8号教学楼"
    }, {
      "id": 9,
      "name": "9号教学楼",
      "latitude": "22.96945",
      "longitude": "113.75461",
      "img": "/img/school/tsg.jpg",
      "description": "9号教学楼"
    }]
  }, {
    name: "校门",
    data: [{
      "id": 1,
      "name": "北门",
      "latitude": "22.97427",
      "longitude": "113.75511",
      "img": "/img/school/tsg.jpg",
      "description": "北门"
    }, {
      "id": 2,
      "name": "东门",
      "latitude": "22.9732",
      "longitude": "113.75779",
      "img": "/img/school/tsg.jpg",
      "description": "东门"
    }, {
      "id": 3,
      "name": "南门",
      "latitude": "22.96919",
      "longitude": "113.75486",
      "img": "/img/school/tsg.jpg",
      "description": "南门"
    }, {
      "id": 4,
      "name": "雅苑门",
      "latitude": "22.97718",
      "longitude": "113.75838",
      "img": "/img/school/tsg.jpg",
      "description": "雅苑门"
    }]
  }, {
    name: "食堂",
    data: [{
      "id": 1,
      "name": "一饭",
      "latitude": "22.974238",
      "longitude": "113.756990",
      "img": "/img/school/tsg.jpg",
      "description": "一饭"
    }, {
      "id": 2,
      "name": "二饭",
      "latitude": "22.970702",
      "longitude": "113.754673",
      "img": "../../img/school/tsg.jpg",
      "description": "二饭"
    }, {
      "id": 3,
      "name": "三饭",
      "latitude": "22.970260",
      "longitude": "113.754510",
      "img": "../../img/school/tsg.jpg",
      "description": "三饭"
    }, {
      "id": 4,
      "name": "四饭",
      "latitude": "22.976881",
      "longitude": "113.756191",
      "img": "../../img/school/tsg.jpg",
      "description": "四饭"
    }]
  }, {
    name: "篮球场",
    data: [{
      "id": 1,
      "name": "北京大学",
      "latitude": "22.97",
      "longitude": "113.75",
      "img": "../../img/school/tsg.jpg",
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 2,
      "name": "西安科技大学",
      "latitude": "22.972",
      "longitude": "113.753",
      "img": "../../img/school/tsg.jpg",
      "description": "西安科技大学"
    }, {
      "id": 3,
      "name": "西北农林科技大学",
      "latitude": "22.9761",
      "longitude": "113.7491",
      "img": "../../img/school/tsg.jpg",
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 4,
      "name": "咸阳师范学院",
      "latitude": "22.97122",
      "longitude": "113.75122",
      "img": "../../img/school/tsg.jpg",
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 5,
      "name": "咸阳师范学院",
      "latitude": "23.07122",
      "longitude": "113.75122",
      "img": "../../img/school/tsg.jpg",
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }, {
      "id": 6,
      "name": "咸阳师范学院",
      "latitude": "22.97122",
      "longitude": "114.05122",
      "img": "../../img/school/tsg.jpg",
      "description": "北京大学（Peking University）简称“北大”（Beida[1]  ），诞生于1898年，初名京师大学堂，是中国近代第一所国立大学，也是第一个以“大学”之名创办的学校，其成立标志着中国近代高等教育的开端。北大是中国近代以来唯一以国家最高学府身份创立的学校，最初也是国家最高教育行政机关，行使教育部职能，统管全国教育。北大催生了中国最早的现代学制，开创了中国最早的文科、理科、社科、农科、医科等大学学科，是近代以来中国高等教育的奠基者。"
    }]
  }
]